// src/utils/pdf.js
import jsPDF from "jspdf";
import "jspdf-autotable";
import { currency } from "./format";

export function exportJobsPDF(jobs) {
  const doc = new jsPDF();
  const now = new Date().toLocaleString();
  doc.setFontSize(14);
  doc.text("Contractor HQ – Job Summary Report", 14, 15);
  doc.setFontSize(10);
  doc.text(`Generated: ${now}`, 14, 22);

  // Totals
  const totals = {
    bid: jobs.reduce((s,j)=>s+Number(j.estimate?.totalBidToClient||0),0),
    expenses: jobs.reduce((s,j)=>s+Number(j.expSum||0),0),
    profit: jobs.reduce((s,j)=>s+Number(j.profit||0),0),
    count: jobs.length
  };
  doc.text(`Total Jobs: ${totals.count}`, 14, 32);
  doc.text(`Total Bid: ${currency(totals.bid)}`, 14, 38);
  doc.text(`Total Expenses: ${currency(totals.expenses)}`, 14, 44);
  doc.text(`Total Profit: ${currency(totals.profit)}`, 14, 50);

  // Table header
  const tableRows = jobs.map(j=>[
    j.title,
    j.client,
    j.trade,
    j.status,
    currency(j.estimate?.totalBidToClient||0),
    currency(j.expSum||0),
    currency(j.profit||0),
    `${j.marginPct?.toFixed(1)||0}%`
  ]);
  doc.autoTable({
    startY: 58,
    head:[["Title","Client","Trade","Status","Bid","Expenses","Profit","Margin"]],
    body:tableRows,
    theme:"grid",
    styles:{fontSize:8},
    headStyles:{fillColor:[41,128,185]},
  });

  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(9);
  doc.text("Generated by Contractor HQ for Dario", 14, finalY + 10);
  doc.save("jobs_report.pdf");
}
